name: "[Job] Terraform Plan & Apply"

permissions:
  id-token: write
  contents: read
  security-events: write
  pull-requests: read

on:
  workflow_call:
    inputs:
      workspace_name:
        description: "The terraform workspace to target for environment actions"
        required: true
        type: string

      oidc_role:
        description: "The OIDC role to assume for AWS access"
        required: true
        type: string

      default_role:
        description: "The default CI role to assume"
        required: true
        type: string

      apply:
        description: "Whether to apply the deployment"
        required: false
        type: boolean
        default: false

    secrets:
      github_access_token:
        description: "Github Token"
        required: true
      snyk_opg_org_token:
        description: "Snyk token for OPG organization"
        required: true

jobs:
  terraform_environment_workflow:
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: ${{ inputs.workspace_name }}
      TF_VAR_default_role: ${{ inputs.default_role }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: "0"
          
      - name: "Parse terraform version"
        id: tf_version
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@722a5f955424aaba01e9ca43d68390cd4048d6e1 # v4.10.2

      - name: "Terraform version [${{ steps.tf_version.outputs.version }}]"
        run: echo "terraform version [${{ steps.tf_version.outputs.version }}]" >> $GITHUB_STEP_SUMMARY

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ steps.tf_version.outputs.version }}
          terraform_wrapper: false

      - name: Format Terraform
        run: terraform fmt -check -recursive

      - uses: terraform-linters/setup-tflint@1cf010d3c7aef302051ccdb68c14c5dc2efa34ef # v6.3.1
        name: Setup TFLint
        with:
          tflint_version: v0.60.0

      - name: Lint Terraform
        id: tf_lint
        run: tflint --recursive

      - name: Configure AWS Credentials For ECR Login
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_MANAGEMENT_ECR_ROLE }}
          role-duration-seconds: 3600
          role-session-name: opg-shared-infrastructure-github-actions-ecr

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
        with:
          registries: 311462405659

      - name: Snky IAC
        id: snyk_iac
        uses: ministryofjustice/opg-github-actions/actions/snyk-iac@722a5f955424aaba01e9ca43d68390cd4048d6e1 # v4.10.2
        with:
          iac_test_directory: "./"
          sarif_filename: "snyk-iac.sarif"
          SNYK_TOKEN: ${{ secrets.snyk_opg_org_token }}

      - name: Upload Snyk IAC scan results to GitHub Security tab
        id: snyk_upload_sarif
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        if: always()
        with:
          category: "Terraform"
          sarif_file: "test-results/snyk-iac.sarif"

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_role }}
          role-duration-seconds: 3600
          role-session-name: opg-shared-infrastructure-github-actions-ci

      - name: Terraform Init
        env:
          TF_WORKSPACE: default
        run: terraform init -input=false

      - name: Terraform Plan
        run: |
          terraform workspace show
          terraform plan -lock-timeout=300s -input=false -parallelism=30 -out=terraform.plan

      - name: Terraform Apply
        if: inputs.apply == true
        run: terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30 terraform.plan
