name: "[Job] Terraform Plan & Apply"

permissions:
  id-token: write
  contents: read
  security-events: write
  pull-requests: read

on:
  workflow_call:
    inputs:
      workspace_name:
        description: "The terraform workspace to target for environment actions"
        required: true
        type: string

      oidc_role:
        description: "The OIDC role to assume for AWS access"
        required: true
        type: string

      default_role:
        description: "The default CI role to assume"
        required: true
        type: string

      apply:
        description: "Whether to apply the deployment"
        required: false
        type: boolean
        default: false

    secrets:
      github_access_token:
        description: "Github Token"
        required: true
      snyk_opg_org_token:
        description: "Snyk token for OPG organization"
        required: true

jobs:
  terraform_environment_workflow:
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: ${{ inputs.workspace_name }}
      TF_VAR_default_role: ${{ inputs.default_role }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: "0"
          
      - name: "Parse terraform version"
        id: tf_version
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@3a15a16fcc221821c2869eecd8822c5d62af2984 # v4.7.0

      - name: "Terraform version [${{ steps.tf_version.outputs.version }}]"
        run: echo "terraform version [${{ steps.tf_version.outputs.version }}]" >> $GITHUB_STEP_SUMMARY

      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ steps.tf_version.outputs.version }}
          terraform_wrapper: false

      - name: Format Terraform
        run: terraform fmt -check -recursive

      - uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
        name: Setup TFLint
        with:
          tflint_version: v0.60.0

      - name: Lint Terraform
        id: tf_lint
        run: tflint --recursive

      - name: Configure AWS Credentials For ECR Login
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_MANAGEMENT_ECR_ROLE }}
          role-duration-seconds: 3600
          role-session-name: opg-shared-infrastructure-github-actions-ecr

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@f2e9fc6c2b355c1890b65e6f6f0e2ac3e6e22f78 # v2.1.2
        with:
          registries: 311462405659

      - name: Snky IAC
        id: snyk_iac
        uses: ministryofjustice/opg-github-actions/actions/snyk-iac@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
        with:
          iac_test_directory: "./"
          sarif_filename: "snyk-iac.sarif"
          SNYK_TOKEN: ${{ secrets.snyk_opg_org_token }}

      - name: Upload Snyk IAC scan results to GitHub Security tab
        id: snyk_upload_sarif
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        if: always()
        with:
          category: "Terraform"
          sarif_file: "test-results/snyk-iac.sarif"

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_role }}
          role-duration-seconds: 3600
          role-session-name: opg-shared-infrastructure-github-actions-ci

      - name: Terraform Init
        env:
          TF_WORKSPACE: default
        run: terraform init -input=false

      - name: Terraform Plan
        run: |
          terraform workspace show
          terraform plan -lock-timeout=300s -input=false -parallelism=30 -out=terraform.plan

      - name: Terraform Apply
        if: inputs.apply == true
        run: terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30 terraform.plan
